  services:
    backend:
      build: ../MVP_Sprint-3_back-end
      image: backend
      ports:
        - "8000:8000"
      volumes:
        - ../MVP_Sprint-3_back-end:/app
  
    frontend:
      build: .
      image: frontend
      ports:
        - "3000:3000"
      volumes:
        - ./app/static:/app/static
        - ./app/index.html:/app/index.html
        - ./app/order_manager.html:/app/order_manager.html
      depends_on:
        - backend